### ISSUE TITLE
CCNP braindir + transfer

### ISSUE THREAD

**Issue by scovitz** [PennLINC/RBC#137]

**Comment by mattcieslak** [comment]
All subjects have freesurfer, but not all subjects have the fmriprep/sub-X/anat directory. the anat/ directory has the transforms we need for braindr. 

So we're running a separate bootstrap that gets the anat/ directories for subjects that have no bold data in all datasets EXCEPT HBN. for HBN there won't be an anat/ directory until fmriprep is run for real.

**Comment by mattcieslak** [comment]
UPDATE: all the datasets have the same situation. if there was no bold then there was no anat/ directory saved, including for HBN
